name: Tinyopt CI

on:
    push: { branches: [ master ] }
    pull_request: { branches: [ master ] }

jobs:
    build:
        runs-on: ${{ matrix.config.os }}
        strategy:
            matrix:
                config:
                    os: [ubuntu-20.04]
                    cxx: [g++-9, g++-10, clang++-9, clang++-11]
                    include :
                        - os: "macos-latest"
                          cxx: "clang++"
        env:
            CXX: $${{ matrix.config.cxx }}
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Build tests and examples.
              run: |
                  ${CXX} --version
                  mkdir build
                  cd build
                  make -j4 -f ../Makefile
            - name: Run unit tests.
              run: build/unit


