name: Tinyopt CI

on:
    push: { branches: [ main ] }
    pull_request: { branches: [ main ] }

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-22.04 ]
                cxx: [ g++-10, g++-13, clang++-13, clang++-15 ]
                cxxstd: [ c++14, c++17, c++20 ]
                exclude: # exclusions to work around https://github.com/actions/runner-images/issues/8659
                    - os: "ubuntu-22.04"
                      cxx: clang++-15
                      cxxstd: c++20
                    - os: "ubuntu-22.04"
                      cxx: clang++-13
                      cxxstd: c++20
                include:
                    - os: "macos-latest"
                      cxx: "clang++"
                      cxxstd: "c++14"
        env:
            CXX: ${{ matrix.cxx }}
            CXXSTD: ${{ matrix.cxxstd }}
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Build tests and examples.
              run: |
                  ${CXX} --version
                  mkdir build
                  cd build
                  make -j4 CXXSTD=${CXXSTD} -f ../Makefile
            - name: Run unit tests.
              run: build/unit


